csp/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

appname = 'csp'
urlpatterns = [
    path('csp/', views.csp, name='csp'),
]
urlpatterns += staticfiles_urlpatterns()

faq/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

appname = 'faq'
urlpatterns = [
    path('faq/', views.faq, name='faq'),
]
urlpatterns += staticfiles_urlpatterns()

home/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

appname = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]
urlpatterns += staticfiles_urlpatterns()

smartprojectassignment/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('', include(('csp.urls', 'csp'), namespace='csp')),
    path('', include(('faq.urls','faq'), namespace='faq')),
]

csp/models.py
from django.db import models
import os

# Create your models here.
class Document(models.Model):
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    name = models.CharField(max_length=255, blank=False)
    file = models.FileField()

    def filename(self):
        return os.path.basename(self.file.name)

    def __str__(self):
        return self.name

faq/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

csp/forms.py
from django import forms
from csp.models import *
#DataFlair #File_Upload
class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ['file']

    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

csp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import *
from .models import *
import openpyxl
from .graph import Graph
from csp import algorithm
# Create your views here.
DOC_FILE_TYPES = ['']

def csp(request):
    if request.method == 'POST':
        file = request.FILES['uploaded-file']
        excel_data = get_excel_data(file) # 1 get_excel_data(file)
        result = assign_theme(excel_data) # 6 assign_theme(excel_data)
        return render(request, 'tescsp.html', {'result' : result}) # 17 pass data hasil proses ke page
    else:
        return render(request, 'tescsp.html')   

def get_excel_data(file):
    wb = openpyxl.load_workbook(file) # 2 buka file pakai openpyxl
    
    worksheet = wb.active # 3 get sheet excel yang active/default

    excel_data = list()
    for row in worksheet.iter_rows(): # 4 proses data dari tiap row di excel
        row_data = dict()
        row_data["nama_mhs"] = row[1].value
        row_data["domisili"] = row[2].value
        excel_data.append(row_data)
    return excel_data # 5 bentuk akhir list of dictionaries

def assign_theme(data):
    assigned_graph = init_constraint_graph() # 7 initiate graph untuk csp
    values = get_nodes_values(assigned_graph) # 12 ambil node dari graph
    for index in data:
        for val in values:
            if index["domisili"] == val:
                index["tema"] = values[val] # 15 cocokkan data domisili dengan node digraph kemudian assign value sesuai di graph
    return data # 16 return hasil penambahan key "tema" pada setiap row data

def init_constraint_graph():
    graph = Graph() # 8 bikin constraint graph
    graph = algorithm.dummy_input(graph) # 9 bikin variabel dummy di graph
    assigned_graph = algorithm.csp(graph) # 10 jalankan algoritma csp ke graph
    return assigned_graph # 11 return graph dengan node yang valuenya sudah diassign

def get_nodes_values(assigned_graph): # 13 get setiap node dari graph yg terbentuk dari algoritma csp
    result = dict()
    for node in assigned_graph.nodes:
        result[str(node.get_name())] = node.get_value()
    return result # 14 bentuk akhir: {"domisili" = "tema"}

faq/views.py
from django.shortcuts import render

# Create your views here.
def faq(request):
    return render(request, 'faq.html')

home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'teshome.html')

csp/templates/tescsp.html
{% load static %}

<!-- {% block title %}Upload Dokumen{% endblock %} -->

{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'footer.css' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>

    <title>Document</title>
</head>

<style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}

    body, html {
      /*height: 100%;*/
    }

    .w3-bar .w3-button {
        padding: 16px;
    }

    #myNavbar {
        background-color: #000B46 !important;
    }

    .container-upload {
        margin-top:10%;
        padding:50px;
    }

    /*<!-- upload box -->*/

    .files input {
    outline: 2px dashed #92b0b3;
    outline-offset: -10px;
    -webkit-transition: outline-offset .15s ease-in-out, background-color .15s linear;
    transition: outline-offset .15s ease-in-out, background-color .15s linear;
    padding: 120px 0px 85px 35%;
    text-align: center !important;
    margin: 0;
    width: 100% !important;
    }

    .files input:focus{     outline: 2px dashed #92b0b3;  outline-offset: -10px;
    -webkit-transition: outline-offset .15s ease-in-out, background-color .15s linear;
    transition: outline-offset .15s ease-in-out, background-color .15s linear; border:1px solid #92b0b3;
    }
    .files{ position:relative}
    .files:after {  pointer-events: none;
    position: absolute;
    top: 60px;
    left: 0;
    width: 50px;
    right: 0;
    height: 56px;
    content: "";
    background-image: url(https://image.flaticon.com/icons/png/128/109/109612.png);
    display: block;
    margin: 0 auto;
    background-size: 100%;
    background-repeat: no-repeat;
    }
    .color input{ background-color:#f1f1f1;}
    .files:before {
    position: absolute;
    bottom: 10px;
    left: 0;  pointer-events: none;
    width: 100%;
    right: 0;
    height: 57px;
    content: " or drag it here. ";
    display: block;
    margin: 0 auto;
    color: #2ea591;
    font-weight: 600;
    text-transform: capitalize;
    text-align: center;
    }

    .submit-btn {
        padding: 15px 40px;
        background: #000B46 !important;
        color: #F9E5BC;
    }

</style>

<body>
    <!-- Navbar (sit on top) -->
    <div class="w3-top">
        <div class="w3-bar w3-white w3-card"  id="myNavbar">
            <a href="{% url 'home:home' %}" style="color: #F9E5BC;" class="w3-bar-item w3-button w3-wide">SmartPA</a>
        <!-- Right-sided navbar links -->
        <div class="w3-right w3-hide-small">
            <!-- <a href="/" style="color: #F9E5BC;" class="w3-bar-item w3-button">Home</a> -->
            <a href="{% url 'home:home' %}" style="color: #F9E5BC;" class="w3-bar-item w3-button">Home</a>
            <!-- <a href="{% url 'csp:csp' %}" style="color: #F9E5BC;" class="w3-bar-item w3-button">Upload</a> -->
            <a href="{% url 'faq:faq' %}" style="color: #F9E5BC;" class="w3-bar-item w3-button">FAQ</a>
        </div>
    
        <!-- Hide right-floated links on small screens and replace them with a menu icon -->
        <a href="javascript:void(0)" class="w3-bar-item w3-button w3-right w3-hide-large w3-hide-medium" onclick="w3_open()">
        <i class="fa fa-bars"></i>
        </a>
        </div>
    </div>

    <!-- Sidebar on small screens when clicking the menu icon -->
    <nav class="w3-sidebar w3-bar-block w3-black w3-card w3-animate-left w3-hide-medium w3-hide-large" style="display:none;" id="mySidebar">
    <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button w3-large w3-padding-16">Close ×</a>
    <a href="{% url 'home:home' %}" onclick="w3_close()" class="w3-bar-item w3-button">Home</a>
    <!-- <a href="/csp" style="color: #F9E5BC;" onclick="w3_close()" class="w3-bar-item w3-button">CSP</a> -->
    <!-- <a href="/csp/upload" style="color: #F9E5BC;" onclick="w3_close()" class="w3-bar-item w3-button">Upload</a> -->
    <a href="#" style="color: #F9E5BC;" class="w3-bar-item w3-button">FAQ</a>

  </nav>


    <div class="container-upload">
        <div class="row">
            <div class="col-md-12">
                <form style="margin-bottom:5%;" method="POST" action="{% url 'csp:csp' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group files">
                        <label>Upload Your File </label>
                        <input type="file" class="form-control" name="uploaded-file">
                    </div>

                    <button type="submit" class="submit-btn btn btn-sm btn-primary" id="js-upload-submit">convert file</button>
                </form>
            </div>
        </div>

        <table class="table table-striped table-bordered">
          {% if result %}
          <thead>
            <tr>
              <th style="background: #000B46; color:white;" scope="col">Nama Mahasiswa</th>
              <th style="background: #000B46; color:white;" scope="col">Domisili</th>
              <th style="background: #000B46; color:white;" scope="col">Tema</th>
            </tr>
          </thead>
          {% endif %}
          <tbody>
            {% for row in result %}
              <tr>
                {% for key, value in row.items %}
                    <td>{{ value }}</td>
                {% endfor %}
              </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>

    <!-- Site footer -->
    <footer style="padding: 20px 100px; background: #040031;" class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6>About</h6>
            <p class="text-justify">SmartProjectAssignment adalah aplikasi dari kelompok OtwCerdas yang menerapkan konsep Sistem Cerdas/AI dengan menerapkan prinsip CSP atau Constraint Satisfaction Problem. Dengan prinsip ini, melakukan pengelompokkan atau penjadwalan akan terasa lebih mudah dan sederhana.</p>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Categories</h6>
            <ul class="footer-links">
              <li><a href="#">Python</a></li>
              <li><a href="#">UI Design</a></li>
              <li><a href="#">Django</a></li>
              <li><a href="#">Java</a></li>
              <li><a href="#">CSP</a></li>
              <li><a href="#">Templates</a></li>
            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Quick Links</h6>
            <ul class="footer-links">
              <li><a href="{% url 'faq:faq' %}">FAQ</a></li>
              <li><a href="#">Contact Us</a></li>
              <li><a href="#">Contribute</a></li>
              <li><a href="#">Privacy Policy</a></li>
              <li><a href="#">Sitemap</a></li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2017 All Rights Reserved by 
         <a href="#">SmartPA.com</a>
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>   
            </ul>
          </div>
        </div>
      </div>
</footer>
   

    <script>
    // Modal Image Gallery
        function onClick(element) {
        document.getElementById("img01").src = element.src;
        document.getElementById("modal01").style.display = "block";
        var captionText = document.getElementById("caption");
        captionText.innerHTML = element.alt;
    }


    // Toggle between showing and hiding the sidebar when clicking the menu icon
    var mySidebar = document.getElementById("mySidebar");

    function w3_open() {
    if (mySidebar.style.display === 'block') {
      mySidebar.style.display = 'none';
    } else {
      mySidebar.style.display = 'block';
    }
  }

    // Close the sidebar with the close button
    function w3_close() {
      mySidebar.style.display = "none";
  }

  //coloring table
  var cells = document.getElementsByTagName('tr'),
    colors = ['73FFDD','FF8B8B','FFFB99','FF96F4','F9E5BC'];

  var count = 0;
  for(var i = 0; i < cells.length; i++) {
    cells[i].style.backgroundColor = '#' + colors[count];
    count+=1;

    if (count == 4){
      count = 0;
    }
  }


  // for(var i = 0; i < cells.length; i++) {
  //   cells[i].style.backgroundColor = '#' + colors[Math.floor(Math.random() * colors.length)];
  // }
  </script>
</body>
</html>
{% endblock %}

csp/templates/upload.html
{% load static %}
{% block content %}

<div class="container">
    <div class="home-page">
        <h1>Ini document upload bre</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-success btn-lg" name="register">
        </form>
    </div>
</div>
{% endblock %}

faq/templates/faq.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'footer.css' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <title>FAQ</title>
</head>

<style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", sans-serif}

    body, html {
      /*height: 100%;*/
    }

    .w3-bar .w3-button {
        padding: 16px;
    }

    #myNavbar {
        background-color: #000B46 !important;
    }

</style>

<body>
    <!-- Navbar (sit on top) -->
    <div class="w3-top">
        <div class="w3-bar w3-white w3-card"  id="myNavbar">
            <a href="{% url 'home:home' %}" style="color: #F9E5BC;" class="w3-bar-item w3-button w3-wide">SmartPA</a>
        <!-- Right-sided navbar links -->
        <div class="w3-right w3-hide-small">
            <!-- <a href="/" style="color: #F9E5BC;" class="w3-bar-item w3-button">Home</a> -->
            <a href="{% url 'home:home' %}" style="color: #F9E5BC;" class="w3-bar-item w3-button">Home</a>
            <a href="{% url 'csp:csp' %}" style="color: #F9E5BC;" class="w3-bar-item w3-button">Upload</a>
            <a href="{% url 'faq:faq' %}" style="color: #F9E5BC;" class="w3-bar-item w3-button">FAQ</a>
        </div>
    
        <!-- Hide right-floated links on small screens and replace them with a menu icon -->
        <a href="javascript:void(0)" class="w3-bar-item w3-button w3-right w3-hide-large w3-hide-medium" onclick="w3_open()">
        <i class="fa fa-bars"></i>
        </a>
        </div>
    </div>

    <!-- Sidebar on small screens when clicking the menu icon -->
    <nav class="w3-sidebar w3-bar-block w3-black w3-card w3-animate-left w3-hide-medium w3-hide-large" style="display:none;" id="mySidebar">
    <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button w3-large w3-padding-16">Close ×</a>
    <a href="{% url 'home:home' %}" onclick="w3_close()" class="w3-bar-item w3-button">Home</a>
    <!-- <a href="/csp" style="color: #F9E5BC;" onclick="w3_close()" class="w3-bar-item w3-button">CSP</a> -->
    <!-- <a href="/csp/upload" style="color: #F9E5BC;" onclick="w3_close()" class="w3-bar-item w3-button">Upload</a> -->
    <a href="#" style="color: #F9E5BC;" class="w3-bar-item w3-button">FAQ</a>

  </nav>
  

    <div style="margin-top:5%" class="container-faq">
    <!-- Bikin Faq-->
        <div class="w3-container w3-padding-large" style="margin-bottom:32px">
            <h4><b>Apa itu SmartPA?</b></h4>
            <p>SPA atau SmartProjectAssignment adalah layanan berbasis website yang dibuat dengan tujuan mempermudah dosen untuk memberikan proyek kelompok kepada mahasiswa dengan berdasarkan domisili masing-masing mahasiswa.</p>
            <hr>
            <h4><b>Bagaimana cara menggunakannya?</b></h4>
            <p>Pengguna cukup mengupload file excel berisi nama-nama mahasiswa serta domisilinya dan SPA akan menghasilkan output kabupaten/kota beserta tema proyek yang akan diberikan kepada mahasiswa yang berdomisili di kabupaten/kota tersebut</p>
            <hr>
            <h4><b>Seberapa cepat waktu mengconvert?</b></h4>
            <p>Tentunya, sangat cepat.</p>
            <hr>
            <h4><b>Apa alasan kami membuat app ini?</b></h4>
            <p>Di tengah pandemi Covid-19 yang melanda seluruh dunia, hampir seluruh kegiatan perkuliahan terpaksa dilakukan secara online, dan tidak dapat dilakukan secara tatap muka, sehingga seluruh mahasiswa melakukan kegiatan PJJ. Supaya pembelajaran tetap kuat meskipun PJJ, setiap mahasiswa diberi proyek berkelompok dan kelompok tersebut didasarkan pada domisili masing-masing mahasiswa. Untuk mempermudah pemberian proyek, dan memastikan kabupaten/kota domisili yang berdekatan tidak diberikan proyek dengan tema yang sama, maka hadirlah Smart Project Assignment (SPA)</p>
        </div>
    </div>
    
    

   <!-- Site footer -->
    <footer style="padding: 20px 100px; background: #040031;" class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6>About</h6>
            <p class="text-justify">SmartProjectAssignment adalah aplikasi dari kelompok OtwCerdas yang menerapkan konsep Sistem Cerdas/AI dengan menerapkan prinsip CSP atau Constraint Satisfaction Problem. Dengan prinsip ini, melakukan pengelompokkan atau penjadwalan akan terasa lebih mudah dan sederhana.</p>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Categories</h6>
            <ul class="footer-links">
              <li><a href="#">Python</a></li>
              <li><a href="#">UI Design</a></li>
              <li><a href="#">Django</a></li>
              <li><a href="#">Java</a></li>
              <li><a href="#">CSP</a></li>
              <li><a href="#">Templates</a></li>
            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Quick Links</h6>
            <ul class="footer-links">
              <li><a href="{% url 'faq:faq' %}">FAQ</a></li>
              <li><a href="#">Contact Us</a></li>
              <li><a href="#">Contribute</a></li>
              <li><a href="#">Privacy Policy</a></li>
              <li><a href="#">Sitemap</a></li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2017 All Rights Reserved by 
         <a href="#">SmartPA.com</a>
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>   
            </ul>
          </div>
        </div>
      </div>
</footer>
   

    <script>
    // Modal Image Gallery
        function onClick(element) {
        document.getElementById("img01").src = element.src;
        document.getElementById("modal01").style.display = "block";
        var captionText = document.getElementById("caption");
        captionText.innerHTML = element.alt;
    }


    // Toggle between showing and hiding the sidebar when clicking the menu icon
    var mySidebar = document.getElementById("mySidebar");

    function w3_open() {
    if (mySidebar.style.display === 'block') {
      mySidebar.style.display = 'none';
    } else {
      mySidebar.style.display = 'block';
    }
  }

    // Close the sidebar with the close button
    function w3_close() {
      mySidebar.style.display = "none";
  }
  </script>
</body>
</html>